# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0002_auto_20170131_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
